version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: navigator-prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
    restart: unless-stopped
    networks:
      - navigator-monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: navigator-grafana
    ports:
      - "3333:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./navigator-dashboard.json:/etc/grafana/provisioning/dashboards/navigator-dashboard.json
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3333
      - GF_INSTALL_PLUGINS=
    restart: unless-stopped
    networks:
      - navigator-monitoring
    depends_on:
      - prometheus

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  navigator-monitoring:
    driver: bridge
